module.exports = {
  apps: [
    {
      name: "localhost-backend",
      script: "dist/app.js", // or app.js
      instances: "max", // run workers = CPU cores
      exec_mode: "cluster", // enables zero-downtime reloads
      autorestart: true,
      max_memory_restart: "300M",
      watch: false,
      node_args: "--sticky-session",
      env: {
        PORT: process.env.PORT,
        NODE_ENV: process.env.NODE_ENV || "production",
        DB_URI: process.env.DB_URI,
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXP_IN: process.env.JWT_EXP_IN,
        ARCJET_ENV: process.env.ARCJET_ENV,
        ARCJET_KEY: process.env.ARCJET_KEY,
        REDIS_TOKEN: process.env.REDIS_TOKEN,
        REDIS_READONLY_TOKEN: process.env.REDIS_READONLY_TOKEN,
        REDIS_URL: process.env.REDIS_URL,
        JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
        JWT_REFRESH_EXP_IN: process.env.JWT_REFRESH_EXP_IN,
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_REGION: process.env.AWS_REGION,
        S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
        OPEN_AI_KEY: process.env.OPEN_AI_KEY,
        GEMINI_KEY: process.env.GEMINI_KEY,
        THIRTY_DAYS: process.env.THIRTY_DAYS,
      },
      env_production: {
        PORT: process.env.PORT,
        NODE_ENV: process.env.NODE_ENV || "production",
        DB_URI: process.env.DB_URI,
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXP_IN: process.env.JWT_EXP_IN,
        ARCJET_ENV: process.env.ARCJET_ENV,
        ARCJET_KEY: process.env.ARCJET_KEY,
        REDIS_TOKEN: process.env.REDIS_TOKEN,
        REDIS_READONLY_TOKEN: process.env.REDIS_READONLY_TOKEN,
        REDIS_URL: process.env.REDIS_URL,
        JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
        JWT_REFRESH_EXP_IN: process.env.JWT_REFRESH_EXP_IN,
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_REGION: process.env.AWS_REGION,
        S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
        OPEN_AI_KEY: process.env.OPEN_AI_KEY,
        GEMINI_KEY: process.env.GEMINI_KEY,
        THIRTY_DAYS: process.env.THIRTY_DAYS,
      },
    },
  ],
};
